catalog/urls.py
from django.urls import path

from catalog import apps, views

app_name = apps.CatalogConfig.name

urlpatterns = [
    path("", views.index, name="index"),
    path("contacts/", views.contacts, name="contacts"),
    path('product/<int:pk>/', views.product_detail, name='product_detail'),
    path('product_create/', views.product_create, name='product_create'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace="catalog")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(verbose_name='описание', **NULLABLE)

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('id', )


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(verbose_name='описание')
    image = models.ImageField(upload_to='products_photo/', verbose_name='превью', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, verbose_name='категория', **NULLABLE)
    price = models.FloatField(default=0.0, verbose_name='цена')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='дата изменения')

    def __str__(self):
        return f"{self.name} {self.category} {self.price}"

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ('id', )


class Contact(models.Model):
    country = models.CharField(max_length=100, verbose_name='страна')
    city = models.CharField(max_length=100, verbose_name='город')
    address = models.CharField(max_length=250, verbose_name='адрес')

    def __str__(self):
        return f"{self.country} {self.city}"

    class Meta:
        verbose_name = 'контакт'
        verbose_name_plural = 'контакты'
        ordering = ('id', )

catalog/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import get_object_or_404, render

from .models import Category, Contact, Product


def index(request):
    product_list = Product.objects.all()
    paginator = Paginator(product_list, 6)
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
    context = {
        'object_list': products,
        'title': 'Главная',
    }
    return render(request, 'catalog/index.html', context)


def product_detail(request, pk):
    product = get_object_or_404(Product, pk=pk)
    context = {
        'object': product,
        'title': product.name,
    }
    return render(request, 'catalog/product_detail.html', context)


def product_create(request):
    context = {
        'categories': Category.objects.all(),
        'title': 'Добавление нового товара',
    }
    if request.method == 'POST':
        name = request.POST.get('name')
        description = request.POST.get('description')
        image = request.FILES.get('image')
        category = request.POST.get('category')
        if category == 'Выберите категорию товара':
            category = None
        price = request.POST.get('price')
        print(123, category)
        Product.objects.create(
            name=name,
            description=description,
            image=image,
            category_id=category,
            price=price,
        )
        context['info'] = f'Товар {name} добавлен'
    return render(request, 'catalog/product_create.html', context)


def contacts(request):
    context = {
        'contact': Contact.objects.get(pk=1),
        'title': 'Контакты',
    }
    if request.method == "POST":
        name = request.POST.get("name")
        phone = request.POST.get("phone")
        message = request.POST.get("message")
        print(f"Новое обращение\nИмя: {name}\nТелефон: {phone}\nСообщение: {message}")
    return render(request, 'catalog/contacts.html', context)

catalog/templates/catalog/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
{% include 'catalog/includes/inc_main_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
    <p class="lead">{{ info }}</p>
</div>

<div class="container">
    {% block content %}
    {% endblock %}
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                ProductStore
                <small class="d-block mb-3 text-muted">&copy; 2024</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="row text-start">
    <div class="col-lg-9 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <table class="table table-striped">
                    <tr>
                        <td class="w-25">Страна</td>
                        <td>{{ contact.country }}</td>
                    </tr>
                    <tr>
                        <td class="w-25">Город</td>
                        <td>{{ contact.city }}</td>
                    </tr>
                    <tr>
                        <td class="w-25">Адрес</td>
                        <td>{{ contact.address }}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    {% include 'catalog/includes/inc_feedback.html' %}
</div>
{% endblock %}

catalog/templates/catalog/home.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Удобный сервис рассылок</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">$ 140</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- Неограниченная лицензия</li>
                        <li>- Поддержка</li>
                        <li>- Установка на сервер</li>
                        <li>- Получение обновлений</li>
                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/includes/inc_feedback.html
<div class="col-lg-3 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name">Имя</label>
                        <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                    </div>
                    <div class="mb-3">
                        <label for="phone">Телефон</label>
                        <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон"
                               required>
                    </div>
                    <div class="mb-3">
                        <label for="message">Сообщение</label>
                        <textarea name="message" class="form-control" id="message" placeholder="Сообщение"
                                  required></textarea>
                    </div>
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                </form>
            </div>
        </div>
    </div>

catalog/templates/catalog/includes/inc_main_menu.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <a href="{% url 'catalog:index' %}" class="navbar-brand">
    <h5 class="my-0 mr-md-auto font-weight-normal">ProductStore</h5>
    </a>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href="/product_create/">Добавить товар</a>
    </nav>
</div>

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}
<div class="row">
    {% for object in object_list %}
    <div class="col-md-4 mb-4">
        <div class="card h-100 box-shadow">
            <div class="card-header">
                <h4 class="card-title text-center">{{ object.name }}</h4>
            </div>
            <img class="card-img-top" src="{{ object.image|get_image }}" alt="{{ object.name }}" width="350"
                 height="200">
            <div class="card-body mt-3">
                <p class="card-text mb-0">Категория: {{ object.category }}</p>
                <p class="card-text mb-0" style="height: 5em; overflow: hidden;">Описание:
                    {{ object.description|slice:'100' }}{% if object.description|length > 100 %}...{% endif %}</p>
                <p class="card-text mb-0">Цена: {{ object.price }} руб.</p>
                <div class="d-flex justify-content-center align-items-center mt-3">
                    <a href="{% url 'catalog:product_detail' object.pk %}"
                       class="btn btn-lg btn-primary mx-2">Подробнее</a>
                    <a href="#" type="button" class="btn btn-lg btn-success mx-2">В корзину</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?page=1">&laquo; Первая</a>
            <a href="?page={{ object_list.previous_page_number }}">Предыдущая</a>
        {% endif %}

        <span class="current">
            Страница {{ object_list.number }} из {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?page={{ object_list.next_page_number }}">Следующая</a>
            <a href="?page={{ object_list.paginator.num_pages }}">Последняя &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

catalog/templates/catalog/product_create.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <div class="card shadow">
                <div class="card-header bg-primary text-white">
                    <h4 class="my-0 font-weight-normal text-center">Форма товара</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="row" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="col-12 mb-3">
                            <label for="name" class="form-label">Наименование товара *</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Введите наименование товара" required>
                        </div>
                        <div class="col-12 mb-3">
                            <label for="description" class="form-label">Описание товара *</label>
                            <textarea name="description" class="form-control" id="description" placeholder="Введите описание товара" required></textarea>
                        </div>
                        <div class="col-12 mb-3">
                            <label for="image" class="form-label">Изображение товара</label>
                            <input class="form-control" type="file" id="image" name="image">
                        </div>
                        <div class="col-12 mb-3">
                            <label for="category" class="form-label">Категория товара</label><br>
                            <select class="form-select" id="category" name="category" aria-label="Select category">
                                <option selected>Выберите категорию товара</option>
                                {% for category in categories %}
                                <option value="{{ category.pk }}">{{ category.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-12 mb-3">
                            <label for="price" class="form-label">Стоимость товара *</label>
                            <input type="number" step="0.01" name="price" class="form-control" id="price" placeholder="Введите стоимость товара" required>
                        </div>
                        <div class="col-12 mb-3">
                            <button type="submit" class="btn btn-primary btn-lg btn-block">Сохранить</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card mt-5">
                <img class="card-img-top" src="{{ object.image|get_image }}" alt="{{ object.name }}">
                <div class="card-body">
                    <p class="card-text"><strong>Категория:</strong> {{ object.category }}</p>
                    <p class="card-text"><strong>Описание:</strong> {{ object.description }}</p>
                    <p class="card-text"><strong>Цена:</strong> {{ object.price }} руб.</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}